### PR TITLE
On complete in use animate fix

### PR DESCRIPTION
**Pull request by cgood92**
There are 2 fixes in this PR:

1. The useEffect condition should run if `onComplete || complete`, not `onCompleteTimeRef.current || complete`.
  - This is because `onCompleteTimeRef.current` is ALWAYS truthy after the first time `useEffect` is ran, because we never set `onCompleteTimeRef.current` to anything falsey.  We do clear the timeout, but that doesn't change the value of `onCompleteTimeRef.current`, which is just a number.
  - This also brings this file into parity with what is happening in the Animate component here: https://github.com/beekai-oss/react-simple-animate/blob/master/src/animate.tsx#L46
2. When updating state, and wanting to include some prior state in that update, then you should always use the callback version of `setState`.  See: https://reactjs.org/docs/hooks-reference.html#functional-updates.
  - In this case, it is particularly problematic because we're calling `setAnimate` in a callback of a `setTimeout`, so it is retrieving quite stale state.  This is causing me problems when implementing this hook.

### CODE REVIEW

**Comment by cgood92** [comment]
@bluebill1049 will you please consider this PR?

**Comment by cgood92** [comment]
My next suggestion would be to update this hook with all the bells and whistles that are currently in the hooks of the `Animate` component.  Then, use this hook in that component.  No need to have duplicated hooks here.

**Comment by bluebill1049** [comment]
thanks for the PR!

**Comment by bluebill1049** [comment]
could you try to npm install again? looks like it's using a private package for some reason.

**Comment by cgood92** [comment]
> could you try to npm install again? looks like it's using a private package for some reason.

I did, I'm so sorry about that.  Thanks.  I have pushed up the yarn.lock changes.

**Review by bluebill1049 — APPROVED** [review]
Thank you for the fix 🙏

**Pull request merged**
